---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ccnp-server
  namespace: ccnp
  labels:
    app: ccnp-server
spec:
  selector:
    matchLabels:
      app: ccnp-server
  template:
    metadata:
      labels:
        app: ccnp-server
    spec:
      tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      containers:
      - name: ccnp-server
        image: docker.io/library/ccnp-server:latest
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command: ["/usr/bin/grpc-health-probe", "-addr=unix:/run/ccnp/uds/ccnp-server.sock"]
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          exec:
            command: ["/usr/bin/grpc-health-probe", "-addr=unix:/run/ccnp/uds/ccnp-server.sock"]
          initialDelaySeconds: 5
          periodSeconds: 10
          failureThreshold: 10
        resources:
          limits:
            tdx.intel.com/tdx-guest: 1
        volumeMounts:
          - name: proc
            mountPath: /proc
          - name: eventlog-entry
            mountPath: /run/firmware/acpi/tables/CCEL
          - name: eventlog-data
            mountPath: /run/firmware/acpi/tables/data/CCEL
          - name: ima-data
            mountPath: /run/kernel/security/
          - name: vsock-port
            mountPath: /etc/tdx-attest.conf
          - name: ccnp-server-config
            mountPath: /etc/policy.yaml
            subPath: policy
      volumes:
        - name: proc
          hostPath:
            path: /proc
            type: Directory
        - name: eventlog-data
          hostPath:
            path: /sys/firmware/acpi/tables/data/CCEL
            type: File
        - name: eventlog-entry
          hostPath:
            path: /sys/firmware/acpi/tables/CCEL
            type: File
        - name: ima-data
          hostPath:
            path: /sys/kernel/security/
            type: Directory
        - name: vsock-port
          hostPath:
            path: /etc/tdx-attest.conf
            type: File
        - name: ccnp-server-config
          configMap:
            name: ccnp-server-config
            items:
              - key: policy_key
                path: policy
      nodeSelector:
        intel.feature.node.kubernetes.io/tdx-guest: "enabled"

---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: ccnp
  name: ccnp-server-config
data:
  policy_key: |-
    backend: ima
    hashAlgorithm: sha384
    measure:
    system:
        withParameter: true
        processes:
        - /usr/bin/containerd
        - /usr/bin/kubelet
        - /usr/bin/containerd-shim-runc-v2
    container:
        isolated: true
    kubernetes:
        withParameter: true
        pods:
        - kube-apiserver
        - kube-scheduler
        - kube-proxy
        - kube-scheduler
        - kube-controller-manager
